import React from "react";
import { type NextPage } from "next";
import Head from "next/head";

const SingePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Profile View</div>
      </main>
    </>
  );
};

export default SingePostPage;
